development:
  adapter: postgresql
  database: foo_api_development
  username: postgres
  host: localhost
  port: 5432

test:
  adapter: postgresql
  database: foo_api_test
  username: postgres
  host: localhost
  port: 5432
